apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: u633dkk2q-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/u633dkk2q-dotnet-basic-gitops